<?php include 'common/frontend/header.phtml';?>
<form class="form-horizontal" method="POST">
	<div class="form-group">
		<label class="control-label col-sm-2">用户名</label>
		<div class="col-sm-10">
			<input type="text" name="username" id="username" placeholder="请输入用户名" class="form-control" required>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2">密码</label>
		<div class="col-sm-10">
			<input type="password" name="password" id="password" class="form-control" required>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<button class="btn btn-default">登陆</button>
		</div>
	</div>
</form>
