<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link href="/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="/js/jquery.js"></script>
<script src="/bootstrap/dist/js/bootstrap.min.js"></script>
<body style="padding-top:50px">
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
	  <ul class="nav navbar-nav">
	   <li class="active"><a href="javascript:void(0)"><?php echo $username;?></a></li>
            <li><a href="/admin/setting">设置</a></li>
            <li><a href="/admin/logout">logout</a></li>
          </ul>
	</div><!--/.navbar-collapse -->
      </div>
    </nav>
<div class="container">
	<div class="row">
		<div class="col-sm-3  sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/admin/role">权限管理<span class="sr-only">(current)</span></a></li>
            <li><a href="/admin/user">用户管理</a></li>
            <li><a href="/admin/category">分类管理</a></li>
            <li><a href="/admin/article">文章管理</a></li>
          </ul>
        </div>
	<div class="col-sm-9">
