<?php include 'common/admin/header.phtml';?>
<form name="addCategory" method="post" class="form-horizontal">
	<div class="form-group">
		<label class="control-label col-sm-2">名称</label>
		<div class="col-sm-10">
			<input type="text" name="name" id="name" class="form-control" placeholder="请输入分类名称" required>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2">是否可以多文章</label>
		<div class="col-sm-10">
			<label class="radio-inline"><input type="radio" name="ismulti" value="2" required>可以</label><label class="radio-inline"><input type="radio" name="ismulti" value="1" required>不可以</label>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<button class="btn btn-primary">提交</button>
		</div>
	</div>
</form>
<?php include 'common/admin/footer.phtml';?>
