<?php include 'common/admin/header.phtml';?>
<form name="addRole" class="form-horizontal" method="POSt">
	<div class="form-group">
		<label class="control-label col-sm-2">模块名称</label>
		<div class="col-sm-10">
			<input type="text" name="modulename" id="modulename" class="form-control" placeholder="请输入模块名称" required>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2">控制器名称</label>
		<div class="col-sm-10">
			<input type="text" name="controllername" id="controllername" class="form-control" placeholder="控制器名称" required>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2">action名称</label>
		<div class="col-sm-10">
			<input type="text" name="actioname" id="actioname" class="form-control" placeholder="请输入action名称" required>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<button class="btn btn-primary">提交</button>
		</div>
	</div>
</form>
<?php include 'common/admin/footer.phtml';?>
