<?php include 'common/admin/header.phtml';?>
<form class="form-horizontal" method="POSt">
	<div class="form-group">
		<label class="control-label col-sm-2">用户名</label>
		<div class="col-sm-10">
			<input type="text" name="username" id="username" class="form-control" placeholder="请填写用户名" required value="">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2">密码</label>
		<div class="col-sm-10">
			<input type="password" name="password" id="password" class="form-control"  required value="">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<button class="btn btn-priamry">提交</button>
		</div>
	</div>
</form>
<?php include 'common/admin/footer.phtml';?>
