<?php include 'common/admin/header.phtml';?>
<form name="editCategory" class="form-horizontal" method="post">
	<div class="form-group">
		<label class="control-label col-sm-2">名称</label>
		<div class="col-sm-10">
			<input type="text" name="name" id="name" class="form-control" placeholder="请输入分类名称" required value="<?php echo $row['name'];?>">
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-2">是否可以多文章</label>
		<div class="col-sm-10">
			
			<label clss="radio-inline"><input type="radio" name="ismulti" id="ismulti"   required value="2" <?php if($row['ismulti'] == 2){echo "checked";}?>>可以</label>
			<label clss="radio-inline"><input type="radio" name="ismulti" id="ismulti"   required value="1" <?php if($row['ismulti'] == 1){echo "checked";}?>>不可以</label>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<button class="btn btn-primary">提交</button>
		</div>
	</div>
</form>
<?php include 'common/admin/footer.phtml';?>
